openapi: 3.0.1
info:
  title: LoccanaInventoryMutations
  description: API Definition of LoccanaInventoryMutations
  version: 1.0.0
servers:
- url: http://localhost:8290/loccana/inventory/mutations
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
  /types:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
